name: Release

on:
  pull_request:
    branches:
    - main
    types:
    - closed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Bump version and create tag
        id: version
        run: |
          # Bump the version using npm version (you can customize this)
          NEW_VERSION=$(npm version patch -m "Release version %s")
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
          echo "tag_name=v$NEW_VERSION" >> $GITHUB_ENV

      - name: Push new version and tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main --tags

      - name: Call Deployment Hook
        run: curl -X POST -d {} "${{ secrets.WEBHOOK_TRIGGER_RELEASE }}"